side_camera:
  camera_name: side_zed
  serial_number: 34108459
  rgb_topic: /side_zed/zed_node/rgb/color/rect/image
  depth_topic: /side_zed/zed_node/depth/depth_registered
  camera_info_topic: /side_zed/zed_node/rgb/color/rect/camera_info
  depth_camera_info_topic: /side_zed/zed_node/depth/depth_registered/camera_info
  optical_frame: side_zed_left_camera_frame_optical
